# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5PjGtKfKh6XXLd9OMvT6k3zLXCzs0ad
"""

import pandas as pd
import unicodedata as ud

df = pd.read_csv("unidades_saude_noroeste_goiania.csv", sep=",")


df = df.applymap(lambda x: x.strip().lower() if isinstance(x, str) else x)

df = df.drop_duplicates()
df = df.fillna("nao informado")



def remover_acentos(x):
    if isinstance(x, str):
        return "".join(
            c for c in ud.normalize("NFKD", x)
            if not ud.combining(c)
        )
    return x

df = df.applymap(remover_acentos)
print(df)


# load
df.to_csv("arquivo_tratado.csv", index=False)

from google.colab import drive
drive.mount('/content/drive')